// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MeyerCorp.Usps.Client
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// </summary>
    public partial interface IUsps : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <param name='firmname'>
        /// </param>
        /// <param name='address1'>
        /// </param>
        /// <param name='address2'>
        /// </param>
        /// <param name='city'>
        /// </param>
        /// <param name='state'>
        /// </param>
        /// <param name='zip5'>
        /// </param>
        /// <param name='zip4'>
        /// </param>
        /// <param name='urbanization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> VerifyAddressWithHttpMessagesAsync(string firmname = default(string), string address1 = default(string), string address2 = default(string), string city = default(string), string state = default(string), string zip5 = default(string), string zip4 = default(string), string urbanization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='zip51'>
        /// </param>
        /// <param name='zip52'>
        /// </param>
        /// <param name='zip53'>
        /// </param>
        /// <param name='zip54'>
        /// </param>
        /// <param name='zip55'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> LookupCityStateWithHttpMessagesAsync(string zip51 = default(string), string zip52 = default(string), string zip53 = default(string), string zip54 = default(string), string zip55 = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='address1'>
        /// </param>
        /// <param name='address2'>
        /// </param>
        /// <param name='city'>
        /// </param>
        /// <param name='firmname'>
        /// </param>
        /// <param name='state'>
        /// </param>
        /// <param name='urbanization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ZipCode>> LookupZipCodeWithHttpMessagesAsync(string address1 = default(string), string address2 = default(string), string city = default(string), string firmname = default(string), string state = default(string), string urbanization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='trackId1'>
        /// </param>
        /// <param name='trackId2'>
        /// </param>
        /// <param name='trackId3'>
        /// </param>
        /// <param name='trackId4'>
        /// </param>
        /// <param name='trackId5'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> TrackingWithHttpMessagesAsync(string trackId1 = default(string), string trackId2 = default(string), string trackId3 = default(string), string trackId4 = default(string), string trackId5 = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> TrackByEmailWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='address1'>
        /// </param>
        /// <param name='address2'>
        /// </param>
        /// <param name='city'>
        /// </param>
        /// <param name='firmname'>
        /// </param>
        /// <param name='state'>
        /// </param>
        /// <param name='urbanization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ZipCode>> ProofOfDeliveryWithHttpMessagesAsync(string address1 = default(string), string address2 = default(string), string city = default(string), string firmname = default(string), string state = default(string), string urbanization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='address1'>
        /// </param>
        /// <param name='address2'>
        /// </param>
        /// <param name='city'>
        /// </param>
        /// <param name='firmname'>
        /// </param>
        /// <param name='state'>
        /// </param>
        /// <param name='urbanization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ZipCode>> ReturnReceiptElectronicWithHttpMessagesAsync(string address1 = default(string), string address2 = default(string), string city = default(string), string firmname = default(string), string state = default(string), string urbanization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
