// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MeyerCorp.Usps.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CityState
    {
        /// <summary>
        /// Initializes a new instance of the CityState class.
        /// </summary>
        public CityState()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CityState class.
        /// </summary>
        public CityState(string zip5 = default(string), string city = default(string), string state = default(string), string id = default(string), string error = default(string))
        {
            Zip5 = zip5;
            City = city;
            State = state;
            Id = id;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip5")]
        public string Zip5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

    }
}
