// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MeyerCorp.Usps.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ZipCode
    {
        /// <summary>
        /// Initializes a new instance of the ZipCode class.
        /// </summary>
        public ZipCode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ZipCode class.
        /// </summary>
        public ZipCode(string firmName = default(string), string address1 = default(string), string address2 = default(string), string city = default(string), string state = default(string), string zip5 = default(string), string zip4 = default(string), string id = default(string), string error = default(string))
        {
            FirmName = firmName;
            Address1 = address1;
            Address2 = address2;
            City = city;
            State = state;
            Zip5 = zip5;
            Zip4 = zip4;
            Id = id;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmName")]
        public string FirmName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address1")]
        public string Address1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address2")]
        public string Address2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip5")]
        public string Zip5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip4")]
        public string Zip4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

    }
}
